name: cryptography

publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

workspace:
  - pkgs/cryptography_plus
  - pkgs/cryptography_plus/example
  - pkgs/cryptography_flutter_plus
  - pkgs/cryptography_flutter_plus/example
  - pkgs/cryptography_flutter_integration_test
  - pkgs/cryptography_test
  - pkgs/jwk_plus
