name: cryptography

publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

workspace:
  - pkgs/cryptography
  - pkgs/cryptography/example
  - pkgs/cryptography_flutter
  - pkgs/cryptography_flutter/example
  - pkgs/cryptography_flutter_integration_test
  - pkgs/cryptography_test
  - pkgs/jwk
