name: Dart CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: gmeligio/flutter-android:3.41.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests (cryptography)
        run: dart test --platform vm
        working-directory: ./cryptography
      - name: Run tests (cryptography_test)
        run: dart test --platform vm
        working-directory: ./cryptography_test
      - name: Run tests (jwk)
        run: dart test --platform vm
        working-directory: ./jwk
      - name: Analyze (cryptography)
        run: dart analyze
        working-directory: ./cryptography
      - name: Analyze (jwk)
        run: dart analyze
        working-directory: ./jwk
