name: Publish

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags: ["[A-z0-9]+-v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  publish:
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      ignore-packages: pkgs/*_test
      use-flutter: true
    permissions:
      id-token: write
      pull-requests: write
